Nie 254 suche balken start
nie-ine/raeber-website pull request #181
Opened 2018-01-16 10:25 UTC by janCstoffregen

Balken fängt erst an, wenn Suche beginnt.

2018-01-16 17:02 UTC, sschuepbach requested changes
Ich finde die Änderung grundsätzlich gut. Was mich allerdings verwirrt hat, ist das anfängliche Fehlen des Ladebalkens, wenn man eine tatsächliche Suche startet. Gerade bei einer langsamen Verbindung (wie aktuell bei mir im Zug) ist es nicht klar, ob die Suche tatsächlich läuft oder nicht. Wäre es nicht möglich, das (Nicht-)Erscheinen des Ladebalkens vom Vorhandensein von Suchparametern abhängig zu machen?

2018-01-17 15:36 UTC, janCstoffregen commented
ok, ich habe es angepasst, was meinst Du? :)

2018-01-18 10:43 UTC, sschuepbach commented
Lieber @janCstoffregen , passt nun alles bestens! Ich merge...

2018-01-18 10:44 UTC, sschuepbach approved these changes

2018-01-18 10:44 UTC, merged